# Generated by Django 2.1.3 on 2018-11-07 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20181031_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cr_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 17, 44, 48, 166917)),
        ),
        migrations.AlterField(
            model_name='post',
            name='cr_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 17, 44, 48, 166537)),
        ),
    ]
