# Generated by Django 2.1.2 on 2018-10-22 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishreview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 23, 12, 1, 75930)),
        ),
        migrations.AlterField(
            model_name='restrewiew',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 23, 12, 1, 75450)),
        ),
    ]
