# Generated by Django 2.1.2 on 2018-10-31 07:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20181022_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 10, 31, 13, 4, 9, 976059))),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='restrewiew',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restrewiew',
            name='user',
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 13, 4, 9, 976059)),
        ),
        migrations.DeleteModel(
            name='RestRewiew',
        ),
    ]
